#!/usr/bin/env bash
set -euo pipefail
export PATH="$HOME/.local/bin:$PATH"
cd "/home/dotmac/projects/agent-swarm-lab/.worktrees/test-telegram"

# Load env
if [[ -f "/home/dotmac/projects/agent-swarm-lab/.env.agent-swarm" ]]; then
    set -a
    source "/home/dotmac/projects/agent-swarm-lab/.env.agent-swarm"
    set +a
fi

# Set DeepSeek as the API base for aider
export OPENAI_API_KEY="${DEEPSEEK_API_KEY}"
export OPENAI_API_BASE="https://api.deepseek.com"

echo "=== Seabone Agent: test-telegram ==="
echo "Task: Create a file called greet.py with a function greet(name) that returns a greeting string"
echo "Branch: agent/test-telegram"
echo "Model: deepseek-chat"
echo "Started: $(date)"
echo "================================"
echo ""

# Run aider in non-interactive mode
aider --model "openai/deepseek-chat"     --no-auto-commits     --yes-always     --message "Create a file called greet.py with a function greet(name) that returns a greeting string"     2>&1 | tee -a "/home/dotmac/projects/agent-swarm-lab/.seabone/logs/test-telegram.log"

AIDER_EXIT=$?

echo ""
echo "=== Agent finished with exit code $AIDER_EXIT ==="

if [[ $AIDER_EXIT -eq 0 ]]; then
    echo "[POST] Committing and pushing changes..."
    cd "/home/dotmac/projects/agent-swarm-lab/.worktrees/test-telegram"

    if git diff --quiet && git diff --cached --quiet; then
        echo "[WARN] No changes were made by the agent."
        # Update task status
        cd "/home/dotmac/projects/agent-swarm-lab"
        jq '(.[] | select(.id == "test-telegram") | .status) = "no_changes"' "/home/dotmac/projects/agent-swarm-lab/.seabone/active-tasks.json" > "/home/dotmac/projects/agent-swarm-lab/.seabone/active-tasks.json.tmp" && mv "/home/dotmac/projects/agent-swarm-lab/.seabone/active-tasks.json.tmp" "/home/dotmac/projects/agent-swarm-lab/.seabone/active-tasks.json"
        "/home/dotmac/projects/agent-swarm-lab/scripts/notify-telegram.sh" "⚠️ *Seabone Agent*: `test-telegram` finished with no changes.
Task: Create a file called greet.py with a function greet(name) that returns a greeting string"
    else
        # Stage and commit
        git add -A
        git commit -m "feat(test-telegram): Create a file called greet.py with a function greet(name) that returns a greeting string

Automated by Seabone agent swarm (aider + deepseek-chat)"

        # Push branch
        git push -u origin "agent/test-telegram"

        # Create PR
        PR_URL=$(gh pr create             --title "[test-telegram] Create a file called greet.py with a function greet(name) that returns a greeting string"             --body "$(cat <<'PRBODY'
## Summary
Automated PR created by Seabone agent swarm.

**Task:** Create a file called greet.py with a function greet(name) that returns a greeting string
**Agent Model:** deepseek-chat
**Branch:** `agent/test-telegram`

---
🤖 Generated by [Seabone Agent Swarm](https://github.com)
PRBODY
)"             --head "agent/test-telegram" 2>&1) || PR_URL="PR creation failed"

        echo "[OK] PR created: $PR_URL"

        # Update task status
        cd "/home/dotmac/projects/agent-swarm-lab"
        jq '(.[] | select(.id == "test-telegram") | .status) = "pr_created"' "/home/dotmac/projects/agent-swarm-lab/.seabone/active-tasks.json" > "/home/dotmac/projects/agent-swarm-lab/.seabone/active-tasks.json.tmp" && mv "/home/dotmac/projects/agent-swarm-lab/.seabone/active-tasks.json.tmp" "/home/dotmac/projects/agent-swarm-lab/.seabone/active-tasks.json"

        # Notify
        "/home/dotmac/projects/agent-swarm-lab/scripts/notify-telegram.sh" "✅ *Seabone Agent*: `test-telegram` completed!
Task: Create a file called greet.py with a function greet(name) that returns a greeting string
PR: $PR_URL"
    fi
else
    echo "[ERROR] Agent failed with exit code $AIDER_EXIT"
    cd "/home/dotmac/projects/agent-swarm-lab"
    jq '(.[] | select(.id == "test-telegram") | .status) = "failed"' "/home/dotmac/projects/agent-swarm-lab/.seabone/active-tasks.json" > "/home/dotmac/projects/agent-swarm-lab/.seabone/active-tasks.json.tmp" && mv "/home/dotmac/projects/agent-swarm-lab/.seabone/active-tasks.json.tmp" "/home/dotmac/projects/agent-swarm-lab/.seabone/active-tasks.json"
    "/home/dotmac/projects/agent-swarm-lab/scripts/notify-telegram.sh" "❌ *Seabone Agent*: `test-telegram` failed (exit $AIDER_EXIT).
Task: Create a file called greet.py with a function greet(name) that returns a greeting string
Check logs: /home/dotmac/projects/agent-swarm-lab/.seabone/logs/test-telegram.log"
fi
