#!/usr/bin/env bash
# spawn-agent.sh — Spawn an isolated coding agent in tmux with git worktree + aider
# Usage: ./spawn-agent.sh <task-id> <description> [--model deepseek-chat]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SEABONE_DIR="$PROJECT_DIR/.seabone"
ACTIVE_FILE="$SEABONE_DIR/active-tasks.json"
CONFIG_FILE="$SEABONE_DIR/config.json"
LOG_DIR="$SEABONE_DIR/logs"
export PATH="$HOME/.local/bin:$PATH"

# Load env
if [[ -f "$PROJECT_DIR/.env.agent-swarm" ]]; then
    set -a
    source "$PROJECT_DIR/.env.agent-swarm"
    set +a
fi

# Args
TASK_ID="${1:?Usage: spawn-agent.sh <task-id> <description> [--model model-name]}"
DESCRIPTION="${2:?Usage: spawn-agent.sh <task-id> <description> [--model model-name]}"
MODEL="${3:-$(jq -r '.model // "deepseek-chat"' "$CONFIG_FILE")}"

# Config
MAX_AGENTS=$(jq -r '.max_concurrent_agents // 3' "$CONFIG_FILE")
BRANCH="agent/${TASK_ID}"
SESSION_NAME="agent-${TASK_ID}"
WORKTREE_DIR="$PROJECT_DIR/.worktrees/${TASK_ID}"
LOG_FILE="$LOG_DIR/${TASK_ID}.log"

# Check concurrency limit
ACTIVE_COUNT=$(jq length "$ACTIVE_FILE" 2>/dev/null || echo 0)
if [[ "$ACTIVE_COUNT" -ge "$MAX_AGENTS" ]]; then
    echo "[ERROR] Max concurrent agents ($MAX_AGENTS) reached. Currently $ACTIVE_COUNT active."
    echo "Run ./scripts/list-tasks.sh to see active tasks."
    exit 1
fi

# Check if task already exists
if jq -e ".[] | select(.id == \"$TASK_ID\")" "$ACTIVE_FILE" > /dev/null 2>&1; then
    echo "[ERROR] Task '$TASK_ID' already exists in active tasks."
    exit 1
fi

# Check if tmux session already exists
if tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
    echo "[ERROR] tmux session '$SESSION_NAME' already exists."
    exit 1
fi

echo "[1/5] Creating git worktree: $BRANCH"
cd "$PROJECT_DIR"
git worktree add "$WORKTREE_DIR" -b "$BRANCH" 2>/dev/null || {
    # Branch might already exist
    git worktree add "$WORKTREE_DIR" "$BRANCH" 2>/dev/null || {
        echo "[ERROR] Failed to create worktree for branch $BRANCH"
        exit 1
    }
}

echo "[2/5] Registering task in Seabone"
TASK_JSON=$(jq -n \
    --arg id "$TASK_ID" \
    --arg desc "$DESCRIPTION" \
    --arg branch "$BRANCH" \
    --arg model "$MODEL" \
    --arg session "$SESSION_NAME" \
    --arg worktree "$WORKTREE_DIR" \
    --arg started "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    '{
        id: $id,
        description: $desc,
        branch: $branch,
        model: $model,
        session: $session,
        worktree: $worktree,
        status: "running",
        retries: 0,
        started_at: $started,
        last_heartbeat: $started
    }')

jq ". + [$TASK_JSON]" "$ACTIVE_FILE" > "${ACTIVE_FILE}.tmp" && mv "${ACTIVE_FILE}.tmp" "$ACTIVE_FILE"

echo "[3/5] Creating aider command script"
AGENT_SCRIPT="$WORKTREE_DIR/.agent-run.sh"
cat > "$AGENT_SCRIPT" << AGENTEOF
#!/usr/bin/env bash
set -euo pipefail
export PATH="\$HOME/.local/bin:\$PATH"
cd "$WORKTREE_DIR"

# Load env
if [[ -f "$PROJECT_DIR/.env.agent-swarm" ]]; then
    set -a
    source "$PROJECT_DIR/.env.agent-swarm"
    set +a
fi

# Set DeepSeek as the API base for aider
export OPENAI_API_KEY="\${DEEPSEEK_API_KEY}"
export OPENAI_API_BASE="https://api.deepseek.com"

echo "=== Seabone Agent: $TASK_ID ==="
echo "Task: $DESCRIPTION"
echo "Branch: $BRANCH"
echo "Model: $MODEL"
echo "Started: \$(date)"
echo "================================"
echo ""

# Run aider in non-interactive mode
aider --model "openai/$MODEL" \
    --no-auto-commits \
    --yes-always \
    --message "$DESCRIPTION" \
    2>&1 | tee -a "$LOG_FILE"

AIDER_EXIT=\$?

echo ""
echo "=== Agent finished with exit code \$AIDER_EXIT ==="

if [[ \$AIDER_EXIT -eq 0 ]]; then
    echo "[POST] Committing and pushing changes..."
    cd "$WORKTREE_DIR"

    if git diff --quiet && git diff --cached --quiet; then
        echo "[WARN] No changes were made by the agent."
        # Update task status
        cd "$PROJECT_DIR"
        jq '(.[] | select(.id == "$TASK_ID") | .status) = "no_changes"' "$ACTIVE_FILE" > "${ACTIVE_FILE}.tmp" && mv "${ACTIVE_FILE}.tmp" "$ACTIVE_FILE"
        "$SCRIPT_DIR/notify-telegram.sh" "⚠️ *Seabone Agent*: \`$TASK_ID\` finished with no changes.
Task: $DESCRIPTION"
    else
        # Stage and commit
        git add -A
        git commit -m "feat($TASK_ID): $DESCRIPTION

Automated by Seabone agent swarm (aider + $MODEL)"

        # Push branch
        git push -u origin "$BRANCH"

        # Create PR
        PR_URL=\$(gh pr create \
            --title "[$TASK_ID] $DESCRIPTION" \
            --body "\$(cat <<'PRBODY'
## Summary
Automated PR created by Seabone agent swarm.

**Task:** $DESCRIPTION
**Agent Model:** $MODEL
**Branch:** \`$BRANCH\`

---
🤖 Generated by [Seabone Agent Swarm](https://github.com)
PRBODY
)" \
            --head "$BRANCH" 2>&1) || PR_URL="PR creation failed"

        echo "[OK] PR created: \$PR_URL"

        # Update task status
        cd "$PROJECT_DIR"
        jq '(.[] | select(.id == "$TASK_ID") | .status) = "pr_created"' "$ACTIVE_FILE" > "${ACTIVE_FILE}.tmp" && mv "${ACTIVE_FILE}.tmp" "$ACTIVE_FILE"

        # Notify
        "$SCRIPT_DIR/notify-telegram.sh" "✅ *Seabone Agent*: \`$TASK_ID\` completed!
Task: $DESCRIPTION
PR: \$PR_URL"
    fi
else
    echo "[ERROR] Agent failed with exit code \$AIDER_EXIT"
    cd "$PROJECT_DIR"
    jq '(.[] | select(.id == "$TASK_ID") | .status) = "failed"' "$ACTIVE_FILE" > "${ACTIVE_FILE}.tmp" && mv "${ACTIVE_FILE}.tmp" "$ACTIVE_FILE"
    "$SCRIPT_DIR/notify-telegram.sh" "❌ *Seabone Agent*: \`$TASK_ID\` failed (exit \$AIDER_EXIT).
Task: $DESCRIPTION
Check logs: $LOG_FILE"
fi
AGENTEOF
chmod +x "$AGENT_SCRIPT"

echo "[4/5] Launching tmux session: $SESSION_NAME"
tmux new-session -d -s "$SESSION_NAME" "bash $AGENT_SCRIPT"

echo "[5/5] Agent spawned successfully!"
echo ""
echo "  Task ID:  $TASK_ID"
echo "  Branch:   $BRANCH"
echo "  Session:  $SESSION_NAME (attach: tmux attach -t $SESSION_NAME)"
echo "  Worktree: $WORKTREE_DIR"
echo "  Log:      $LOG_FILE"
echo ""

# Notify
"$SCRIPT_DIR/notify-telegram.sh" "🚀 *Seabone Agent Spawned*: \`$TASK_ID\`
Task: $DESCRIPTION
Model: $MODEL" 2>/dev/null || true
